### ISSUE TITLE
Error running main.py

### ISSUE THREAD

**Issue by tugrul512bit** [Golova1111/mspaint_genetic_algo#2]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    demo_pic = image.imread('pic/berlin_xsm.jpg').astype(np.int16)
  File "/home/tugrul/anaconda3/lib/python3.7/site-packages/matplotlib/image.py", line 1417, in imread
    with Image.open(fname) as image:
  File "/home/tugrul/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'pic/berlin_xsm.jpg'

My system: Ubuntu 18.04LTS, FX8150, GT1030, K420 (x2), 4GB RAM

**Comment by Golova1111** [comment]
The file `pic/berlin_xsm.jpg` is an initial image file that should be processed by the algorithm
Upload your own .jpg/.jpeg image (but not .png) to the "pic" folder and substitute the name of the file in the main script

(will update the readme and add this info, thanks)

**Comment by Golova1111** [comment]
you can use '[demo_pic.jpg](https://github.com/Golova1111/mspaint_genetic_algo/blob/master/pic/demo_pic.jpg)' that is committed, so just substitute `pic/berlin_xsm.jpg` with `pic/demo_pic.jpg` in the main.py script

**Comment by tugrul512bit** [comment]
Ok, this problem solved and opened up a new problem:

`
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    init(demo_pic)
  File "/home/tugrul/Downloads/vramdisk/mspaint_genetic_algo-master/ga_run.py", line 19, in init
    d_picture = cuda.to_device(demo_pic)
  File "/home/tugrul/.local/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 223, in _require_cuda_context
    with _runtime.ensure_context():
  File "/home/tugrul/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/tugrul/.local/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 123, in ensure_context
    newctx = self.get_or_create_context(None)
  File "/home/tugrul/.local/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 138, in get_or_create_context
    return self._get_or_create_context_uncached(devnum)
  File "/home/tugrul/.local/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 153, in _get_or_create_context_uncached
    return self._activate_context_for(0)
  File "/home/tugrul/.local/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 169, in _activate_context_for
    newctx = gpu.get_primary_context()
  File "/home/tugrul/.local/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 529, in get_primary_context
    driver.cuDevicePrimaryCtxRetain(byref(hctx), self.id)
  File "/home/tugrul/.local/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/tugrul/.local/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [2] Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_OUT_OF_MEMORY

`

**Comment by Golova1111** [comment]
Sorry for the long answer from my side

It is hard to answer this question for sure, do you use the `demo_pic.jpg` as the source?
The possible answer is that the size of the picture should be multiplied by 20

from the readme: `Important: the size of the initial picture (height x width) should be multiple be 20, e.g. 180x240 (this limitation goes from the current cuda realization)`

Another probable answer is that the size of the picture is big enough (e.g. 2000x3000)

BTW, what is your CUDA version? (output of the `nvcc --version` command)

**Comment by Golova1111** [comment]
I have made a fix that most probably will help you, please pull new changes and retry

**Comment by tugrul512bit** [comment]
Downloaded new version and it works

```
Epoch 0: best_score: 28562554387, improved, time: 0.0004887580871582031, delta 0
/home/tugrul/Downloads/vramdisk/mspaint_genetic_algo-master(1)/mspaint_genetic_algo-master/Color.py:238: RuntimeWarning: divide by zero encountered in true_divide
  delta = 1 / delta
Epoch 1: best_score: 28561567378, improved, time: 3.483412027359009, delta 0
Epoch 2: best_score: 26059836597, improved, time: 6.3118250370025635, delta 0
Epoch 3: best_score: 24100076967, improved, time: 9.166004419326782, delta 0

```

Thank you. I think GT1030 is not very good alone :) and it has 50% utilization but it works and optimizes the best_score which I guess its the pixel difference from original image.

**Comment by Golova1111** [comment]
No, the `FileNotFoundError` error here is only my fault. I updated the code and removed the hardcoded path from the source  (`/home/vadym/University..`). Please pull and restart

Thanks for reporting the errors!

**Comment by tugrul512bit** [comment]
Now it works fully

[gt1030](https://i2.paste.pics/63d034d7970127786fd7ddce702203aa.png?trs=0041365f4a5ce361f449f7a80a0c95503d157016898eb9dc8c3d029c1817bab1)

How does 75 epochs in 234 seconds (of 100MHz overclocked GT1030) compare to other GPUs? Do you have benchmarks?

**Comment by Golova1111** [comment]
my own [GTX 1060 6GB](https://i.imgur.com/zrQraZh.png), around 44 seconds for 64 epochs (final result for the set of 2 figures)

**Comment by Golova1111** [comment]
You can speed up the algorithm by simply sending the smaller image, instead of 480x360 as now put 240x180, it is still enough to recreate the image with good quality and will reduce the time around 2 times

(the fine-tuned result of recreating demo image from resized 240x180 copy: [img](https://i.imgur.com/mmIGsPF.png)), tooks around 4.5 hours on my GPU, good enough results ([img](https://i.imgur.com/GRndNV7.png)) are available in a half an hour

**Comment by tugrul512bit** [comment]
I think my CPU (fx8150 at 2.1GHz) makes some bottleneck with all python programs overall. Nice project. Have a nice day.
